/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sultan Leosko
 */
public class JFrame_aplikasi_klinik extends javax.swing.JFrame {
int biaya_admin, konsultasi, obat, diskon, total_harga, total;
    /**
     * Creates new form JFrame_aplikasi_klinik
     */
    public JFrame_aplikasi_klinik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama_dokter = new javax.swing.JTextField();
        waktu_praktek = new javax.swing.JTextField();
        radio_umum = new javax.swing.JRadioButton();
        radio_gigi = new javax.swing.JRadioButton();
        radio_saraf = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_lama = new javax.swing.JTextField();
        combo_ruang = new javax.swing.JComboBox();
        text_harga = new javax.swing.JTextField();
        text_diskon = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomer_pasien = new javax.swing.JTextField();
        nama_pasien = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        check_admin = new javax.swing.JCheckBox();
        check_konsul = new javax.swing.JCheckBox();
        check_obat = new javax.swing.JCheckBox();
        text_admin = new javax.swing.JTextField();
        text_konsul = new javax.swing.JTextField();
        text_obat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text_total = new javax.swing.JTextField();
        button_bersih = new javax.swing.JButton();
        button_keluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jenis Poli"));

        jLabel2.setText("Waktu Praktek");

        buttonGroup1.add(radio_umum);
        radio_umum.setText("Umum");
        radio_umum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_umumActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_gigi);
        radio_gigi.setText("Gigi");
        radio_gigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gigiActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_saraf);
        radio_saraf.setText("Saraf");
        radio_saraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_sarafActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Dokter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(waktu_praktek))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_umum)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addComponent(radio_gigi)
                                .addGap(33, 33, 33)
                                .addComponent(radio_saraf))
                            .addComponent(nama_dokter))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_umum)
                    .addComponent(radio_gigi)
                    .addComponent(radio_saraf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(waktu_praktek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Lama Inap");

        jLabel4.setText("Nama Ruang");

        jLabel5.setText("Harga / Hari");

        jLabel6.setText("Diskon");

        combo_ruang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kenanga", "Mawar", "Melati" }));
        combo_ruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_ruangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_lama)
                    .addComponent(combo_ruang, 0, 154, Short.MAX_VALUE)
                    .addComponent(text_harga)
                    .addComponent(text_diskon))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pasien"));

        jLabel7.setText("Nomer Pasien");

        jLabel8.setText("Nama");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomer_pasien)
                    .addComponent(nama_pasien))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nomer_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Perincian Biaya"));

        check_admin.setText("Administrasi");
        check_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_adminActionPerformed(evt);
            }
        });

        check_konsul.setText("Konsultasi Dokter");
        check_konsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_konsulActionPerformed(evt);
            }
        });

        check_obat.setText("Obat");
        check_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_obatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_admin)
                    .addComponent(check_konsul)
                    .addComponent(check_obat))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_admin)
                    .addComponent(text_konsul)
                    .addComponent(text_obat))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_admin)
                    .addComponent(text_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_konsul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_konsul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_obat)
                    .addComponent(text_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Total");

        button_bersih.setText("Bersih");
        button_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bersihActionPerformed(evt);
            }
        });

        button_keluar.setText("Keluar");
        button_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_keluarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("KLINIK INSPIRASIONLINE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(text_total, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_bersih)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_keluar)
                                .addGap(44, 44, 44)))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(text_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_bersih)
                            .addComponent(button_keluar))))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_umumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_umumActionPerformed
        // TODO add your handling code here:
        if(radio_umum.isSelected()) {
            nama_dokter.setText("Dr. Sugiharto");
            waktu_praktek.setText("Pagi");
        }
    }//GEN-LAST:event_radio_umumActionPerformed

    private void radio_gigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_gigiActionPerformed
        // TODO add your handling code here:
        if(radio_gigi.isSelected()) {
            nama_dokter.setText("Dr. Wahyu Nugroho");
            waktu_praktek.setText("Sore");
        }
    }//GEN-LAST:event_radio_gigiActionPerformed

    private void radio_sarafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_sarafActionPerformed
        // TODO add your handling code here:
        if(radio_saraf.isSelected()) {
            nama_dokter.setText("Dr. Dalhar");
            waktu_praktek.setText("Malam");
        }
    }//GEN-LAST:event_radio_sarafActionPerformed

    private void combo_ruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_ruangActionPerformed
        // TODO add your handling code here:
        if(combo_ruang.getSelectedItem().equals("Kenanga")) {
            text_harga.setText("200000");
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totalharga = harga * lama;
            int potongan1 = totalharga * 10/100;
            int potongan2 = totalharga * 0;
            if(lama > 4) {
                diskon = potongan1;
                text_diskon.setText(Integer.toString(potongan1));
                total = totalharga - diskon + biaya_admin + obat + konsultasi;
                text_total.setText(String.valueOf(total));
            }
            else {
                diskon = potongan2;
                text_diskon.setText(Integer.toString(potongan2));
                total = totalharga - diskon + biaya_admin + obat + konsultasi;
                text_total.setText(String.valueOf(total));
            }
        }
        else if(combo_ruang.getSelectedItem().equals("Mawar")) {
            text_harga.setText("300000");
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totalharga = harga * lama;
            int potongan1 = totalharga * 10/100;
            int potongan2 = totalharga * 0;
            if(lama > 4) {
                diskon = potongan1;
                text_diskon.setText(Integer.toString(potongan1));
                total = totalharga - diskon + biaya_admin + obat + konsultasi;
                text_total.setText(String.valueOf(total));
            }
            else {
                diskon = potongan2;
                text_diskon.setText(Integer.toString(potongan2));
                total = totalharga - diskon + biaya_admin + obat + konsultasi;
                text_total.setText(String.valueOf(total));
            }
        }
        else if(combo_ruang.getSelectedItem().equals("Melati")) {
            text_harga.setText("400000");
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totalharga = harga * lama;
            int potongan1 = totalharga * 10/100;
            int potongan2 = totalharga * 0;
            if(lama > 4) {
                diskon = potongan1;
                text_diskon.setText(Integer.toString(potongan1));
                total = totalharga - diskon + biaya_admin + obat + konsultasi;
                text_total.setText(String.valueOf(total));
            }
            else {
                diskon = potongan2;
                text_diskon.setText(Integer.toString(potongan2));
                total = totalharga - diskon + biaya_admin + obat + konsultasi;
                text_total.setText(String.valueOf(total));
            }
        }
    }//GEN-LAST:event_combo_ruangActionPerformed

    private void check_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_adminActionPerformed
        // TODO add your handling code here:
        if(check_admin.isSelected()) {
            biaya_admin = 5000;
            text_admin.setText(String.valueOf(biaya_admin));
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totaldiskon = Integer.parseInt(text_diskon.getText());
            total = (harga * lama) - totaldiskon + biaya_admin + konsultasi + obat;
            text_total.setText(String.valueOf(total));
        }
        else {
            biaya_admin = 0;
            text_admin.setText(String.valueOf(biaya_admin));
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totaldiskon = Integer.parseInt(text_diskon.getText());
            total = (harga * lama) - totaldiskon + biaya_admin + konsultasi + obat;
            text_total.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_check_adminActionPerformed

    private void check_konsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_konsulActionPerformed
        // TODO add your handling code here:
        if(check_konsul.isSelected()) {
            konsultasi = 20000;
            text_konsul.setText(String.valueOf(konsultasi));
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totaldiskon = Integer.parseInt(text_diskon.getText());
            total = (harga * lama) - totaldiskon + biaya_admin + konsultasi + obat;
            text_total.setText(String.valueOf(total));
        }
        else {
            konsultasi = 0;
            text_konsul.setText(String.valueOf(konsultasi));
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totaldiskon = Integer.parseInt(text_diskon.getText());
            total = (harga * lama) - totaldiskon + biaya_admin + konsultasi + obat;
            text_total.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_check_konsulActionPerformed

    private void check_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_obatActionPerformed
        // TODO add your handling code here:
        if(check_obat.isSelected()) {
            obat = 50000;
            text_obat.setText(String.valueOf(obat));
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totaldiskon = Integer.parseInt(text_diskon.getText());
            total = (harga * lama) - totaldiskon + biaya_admin + konsultasi + obat;
            text_total.setText(String.valueOf(total));
        }
        else {
            obat = 0;
            text_obat.setText(String.valueOf(obat));
            int harga = Integer.parseInt(text_harga.getText());
            int lama = Integer.parseInt(text_lama.getText());
            int totaldiskon = Integer.parseInt(text_diskon.getText());
            total = (harga * lama) - totaldiskon + biaya_admin + konsultasi + obat;
            text_total.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_check_obatActionPerformed

    private void button_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bersihActionPerformed
        // TODO add your handling code here:
        check_konsul.setSelected(false);
        text_konsul.setText("");
        check_admin.setSelected(false);
        text_admin.setText("");
        check_obat.setSelected(false);
        text_obat.setText("");
        combo_ruang.setSelectedIndex(0);
        text_lama.setText("");
        text_harga.setText("");
        nama_dokter.setText("");
        text_diskon.setText("");
        buttonGroup1.clearSelection();
        text_total.setText("");
        nomer_pasien.setText("");
        nama_pasien.setText("");
        waktu_praktek.setText("");
    }//GEN-LAST:event_button_bersihActionPerformed

    private void button_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_aplikasi_klinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_aplikasi_klinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_aplikasi_klinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_aplikasi_klinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_aplikasi_klinik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_bersih;
    private javax.swing.JButton button_keluar;
    private javax.swing.JCheckBox check_admin;
    private javax.swing.JCheckBox check_konsul;
    private javax.swing.JCheckBox check_obat;
    private javax.swing.JComboBox combo_ruang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nama_dokter;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField nomer_pasien;
    private javax.swing.JRadioButton radio_gigi;
    private javax.swing.JRadioButton radio_saraf;
    private javax.swing.JRadioButton radio_umum;
    private javax.swing.JTextField text_admin;
    private javax.swing.JTextField text_diskon;
    private javax.swing.JTextField text_harga;
    private javax.swing.JTextField text_konsul;
    private javax.swing.JTextField text_lama;
    private javax.swing.JTextField text_obat;
    private javax.swing.JTextField text_total;
    private javax.swing.JTextField waktu_praktek;
    // End of variables declaration//GEN-END:variables
}
